<?php
// DO NOT EDIT! Generated by Protobuf-PHP protoc plugin 0.9.4
// Source: paymentrequest.proto
//   Date: 2014-02-14 19:45:38

namespace payments {

  class PaymentFrequencyType extends \DrSlump\Protobuf\Enum {
    const WEEKLY = 1;
    const MONTHLY = 2;
    const QUARTERLY = 3;
    const ANNUAL = 4;
  }
}
namespace payments {

  class Output extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $amount = 0;
    
    /**  @var string */
    public $script = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'payments.Output');

      // OPTIONAL UINT64 amount = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "amount";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = 0;
      $descriptor->addField($f);

      // REQUIRED BYTES script = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "script";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <amount> has a value
     *
     * @return boolean
     */
    public function hasAmount(){
      return $this->_has(1);
    }
    
    /**
     * Clear <amount> value
     *
     * @return \payments\Output
     */
    public function clearAmount(){
      return $this->_clear(1);
    }
    
    /**
     * Get <amount> value
     *
     * @return int
     */
    public function getAmount(){
      return $this->_get(1);
    }
    
    /**
     * Set <amount> value
     *
     * @param int $value
     * @return \payments\Output
     */
    public function setAmount( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <script> has a value
     *
     * @return boolean
     */
    public function hasScript(){
      return $this->_has(2);
    }
    
    /**
     * Clear <script> value
     *
     * @return \payments\Output
     */
    public function clearScript(){
      return $this->_clear(2);
    }
    
    /**
     * Get <script> value
     *
     * @return string
     */
    public function getScript(){
      return $this->_get(2);
    }
    
    /**
     * Set <script> value
     *
     * @param string $value
     * @return \payments\Output
     */
    public function setScript( $value){
      return $this->_set(2, $value);
    }
  }
}

namespace payments {

  class PaymentDetails extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $network = "main";
    
    /**  @var \payments\Output[]  */
    public $outputs = array();
    
    /**  @var int */
    public $time = null;
    
    /**  @var int */
    public $expires = null;
    
    /**  @var string */
    public $memo = null;
    
    /**  @var string */
    public $payment_url = null;
    
    /**  @var string */
    public $merchant_data = null;
    
    /**  @var string */
    public $serialized_recurring_payment_details = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'payments.PaymentDetails');

      // OPTIONAL STRING network = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "network";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = "main";
      $descriptor->addField($f);

      // REPEATED MESSAGE outputs = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "outputs";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\payments\Output';
      $descriptor->addField($f);

      // REQUIRED UINT64 time = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "time";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // OPTIONAL UINT64 expires = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "expires";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING memo = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "memo";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL STRING payment_url = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "payment_url";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL BYTES merchant_data = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "merchant_data";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL BYTES serialized_recurring_payment_details = 8
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 8;
      $f->name      = "serialized_recurring_payment_details";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <network> has a value
     *
     * @return boolean
     */
    public function hasNetwork(){
      return $this->_has(1);
    }
    
    /**
     * Clear <network> value
     *
     * @return \payments\PaymentDetails
     */
    public function clearNetwork(){
      return $this->_clear(1);
    }
    
    /**
     * Get <network> value
     *
     * @return string
     */
    public function getNetwork(){
      return $this->_get(1);
    }
    
    /**
     * Set <network> value
     *
     * @param string $value
     * @return \payments\PaymentDetails
     */
    public function setNetwork( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <outputs> has a value
     *
     * @return boolean
     */
    public function hasOutputs(){
      return $this->_has(2);
    }
    
    /**
     * Clear <outputs> value
     *
     * @return \payments\PaymentDetails
     */
    public function clearOutputs(){
      return $this->_clear(2);
    }
    
    /**
     * Get <outputs> value
     *
     * @param int $idx
     * @return \payments\Output
     */
    public function getOutputs($idx = NULL){
      return $this->_get(2, $idx);
    }
    
    /**
     * Set <outputs> value
     *
     * @param \payments\Output $value
     * @return \payments\PaymentDetails
     */
    public function setOutputs(\payments\Output $value, $idx = NULL){
      return $this->_set(2, $value, $idx);
    }
    
    /**
     * Get all elements of <outputs>
     *
     * @return \payments\Output[]
     */
    public function getOutputsList(){
     return $this->_get(2);
    }
    
    /**
     * Add a new element to <outputs>
     *
     * @param \payments\Output $value
     * @return \payments\PaymentDetails
     */
    public function addOutputs(\payments\Output $value){
     return $this->_add(2, $value);
    }
    
    /**
     * Check if <time> has a value
     *
     * @return boolean
     */
    public function hasTime(){
      return $this->_has(3);
    }
    
    /**
     * Clear <time> value
     *
     * @return \payments\PaymentDetails
     */
    public function clearTime(){
      return $this->_clear(3);
    }
    
    /**
     * Get <time> value
     *
     * @return int
     */
    public function getTime(){
      return $this->_get(3);
    }
    
    /**
     * Set <time> value
     *
     * @param int $value
     * @return \payments\PaymentDetails
     */
    public function setTime( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <expires> has a value
     *
     * @return boolean
     */
    public function hasExpires(){
      return $this->_has(4);
    }
    
    /**
     * Clear <expires> value
     *
     * @return \payments\PaymentDetails
     */
    public function clearExpires(){
      return $this->_clear(4);
    }
    
    /**
     * Get <expires> value
     *
     * @return int
     */
    public function getExpires(){
      return $this->_get(4);
    }
    
    /**
     * Set <expires> value
     *
     * @param int $value
     * @return \payments\PaymentDetails
     */
    public function setExpires( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <memo> has a value
     *
     * @return boolean
     */
    public function hasMemo(){
      return $this->_has(5);
    }
    
    /**
     * Clear <memo> value
     *
     * @return \payments\PaymentDetails
     */
    public function clearMemo(){
      return $this->_clear(5);
    }
    
    /**
     * Get <memo> value
     *
     * @return string
     */
    public function getMemo(){
      return $this->_get(5);
    }
    
    /**
     * Set <memo> value
     *
     * @param string $value
     * @return \payments\PaymentDetails
     */
    public function setMemo( $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <payment_url> has a value
     *
     * @return boolean
     */
    public function hasPaymentUrl(){
      return $this->_has(6);
    }
    
    /**
     * Clear <payment_url> value
     *
     * @return \payments\PaymentDetails
     */
    public function clearPaymentUrl(){
      return $this->_clear(6);
    }
    
    /**
     * Get <payment_url> value
     *
     * @return string
     */
    public function getPaymentUrl(){
      return $this->_get(6);
    }
    
    /**
     * Set <payment_url> value
     *
     * @param string $value
     * @return \payments\PaymentDetails
     */
    public function setPaymentUrl( $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <merchant_data> has a value
     *
     * @return boolean
     */
    public function hasMerchantData(){
      return $this->_has(7);
    }
    
    /**
     * Clear <merchant_data> value
     *
     * @return \payments\PaymentDetails
     */
    public function clearMerchantData(){
      return $this->_clear(7);
    }
    
    /**
     * Get <merchant_data> value
     *
     * @return string
     */
    public function getMerchantData(){
      return $this->_get(7);
    }
    
    /**
     * Set <merchant_data> value
     *
     * @param string $value
     * @return \payments\PaymentDetails
     */
    public function setMerchantData( $value){
      return $this->_set(7, $value);
    }
    
    /**
     * Check if <serialized_recurring_payment_details> has a value
     *
     * @return boolean
     */
    public function hasSerializedRecurringPaymentDetails(){
      return $this->_has(8);
    }
    
    /**
     * Clear <serialized_recurring_payment_details> value
     *
     * @return \payments\PaymentDetails
     */
    public function clearSerializedRecurringPaymentDetails(){
      return $this->_clear(8);
    }
    
    /**
     * Get <serialized_recurring_payment_details> value
     *
     * @return string
     */
    public function getSerializedRecurringPaymentDetails(){
      return $this->_get(8);
    }
    
    /**
     * Set <serialized_recurring_payment_details> value
     *
     * @param string $value
     * @return \payments\PaymentDetails
     */
    public function setSerializedRecurringPaymentDetails( $value){
      return $this->_set(8, $value);
    }
  }
}

namespace payments {

  class PaymentRequest extends \DrSlump\Protobuf\Message {

    /**  @var int */
    public $payment_details_version = 1;
    
    /**  @var string */
    public $pki_type = "none";
    
    /**  @var string */
    public $pki_data = null;
    
    /**  @var string */
    public $serialized_payment_details = null;
    
    /**  @var string */
    public $signature = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'payments.PaymentRequest');

      // OPTIONAL UINT32 payment_details_version = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "payment_details_version";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT32;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = 1;
      $descriptor->addField($f);

      // OPTIONAL STRING pki_type = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "pki_type";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->default   = "none";
      $descriptor->addField($f);

      // OPTIONAL BYTES pki_data = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "pki_data";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REQUIRED BYTES serialized_payment_details = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "serialized_payment_details";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // OPTIONAL BYTES signature = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "signature";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <payment_details_version> has a value
     *
     * @return boolean
     */
    public function hasPaymentDetailsVersion(){
      return $this->_has(1);
    }
    
    /**
     * Clear <payment_details_version> value
     *
     * @return \payments\PaymentRequest
     */
    public function clearPaymentDetailsVersion(){
      return $this->_clear(1);
    }
    
    /**
     * Get <payment_details_version> value
     *
     * @return int
     */
    public function getPaymentDetailsVersion(){
      return $this->_get(1);
    }
    
    /**
     * Set <payment_details_version> value
     *
     * @param int $value
     * @return \payments\PaymentRequest
     */
    public function setPaymentDetailsVersion( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <pki_type> has a value
     *
     * @return boolean
     */
    public function hasPkiType(){
      return $this->_has(2);
    }
    
    /**
     * Clear <pki_type> value
     *
     * @return \payments\PaymentRequest
     */
    public function clearPkiType(){
      return $this->_clear(2);
    }
    
    /**
     * Get <pki_type> value
     *
     * @return string
     */
    public function getPkiType(){
      return $this->_get(2);
    }
    
    /**
     * Set <pki_type> value
     *
     * @param string $value
     * @return \payments\PaymentRequest
     */
    public function setPkiType( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <pki_data> has a value
     *
     * @return boolean
     */
    public function hasPkiData(){
      return $this->_has(3);
    }
    
    /**
     * Clear <pki_data> value
     *
     * @return \payments\PaymentRequest
     */
    public function clearPkiData(){
      return $this->_clear(3);
    }
    
    /**
     * Get <pki_data> value
     *
     * @return string
     */
    public function getPkiData(){
      return $this->_get(3);
    }
    
    /**
     * Set <pki_data> value
     *
     * @param string $value
     * @return \payments\PaymentRequest
     */
    public function setPkiData( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <serialized_payment_details> has a value
     *
     * @return boolean
     */
    public function hasSerializedPaymentDetails(){
      return $this->_has(4);
    }
    
    /**
     * Clear <serialized_payment_details> value
     *
     * @return \payments\PaymentRequest
     */
    public function clearSerializedPaymentDetails(){
      return $this->_clear(4);
    }
    
    /**
     * Get <serialized_payment_details> value
     *
     * @return string
     */
    public function getSerializedPaymentDetails(){
      return $this->_get(4);
    }
    
    /**
     * Set <serialized_payment_details> value
     *
     * @param string $value
     * @return \payments\PaymentRequest
     */
    public function setSerializedPaymentDetails( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <signature> has a value
     *
     * @return boolean
     */
    public function hasSignature(){
      return $this->_has(5);
    }
    
    /**
     * Clear <signature> value
     *
     * @return \payments\PaymentRequest
     */
    public function clearSignature(){
      return $this->_clear(5);
    }
    
    /**
     * Get <signature> value
     *
     * @return string
     */
    public function getSignature(){
      return $this->_get(5);
    }
    
    /**
     * Set <signature> value
     *
     * @param string $value
     * @return \payments\PaymentRequest
     */
    public function setSignature( $value){
      return $this->_set(5, $value);
    }
  }
}

namespace payments {

  class X509Certificates extends \DrSlump\Protobuf\Message {

    /**  @var string[]  */
    public $certificate = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'payments.X509Certificates');

      // REPEATED BYTES certificate = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "certificate";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <certificate> has a value
     *
     * @return boolean
     */
    public function hasCertificate(){
      return $this->_has(1);
    }
    
    /**
     * Clear <certificate> value
     *
     * @return \payments\X509Certificates
     */
    public function clearCertificate(){
      return $this->_clear(1);
    }
    
    /**
     * Get <certificate> value
     *
     * @param int $idx
     * @return string
     */
    public function getCertificate($idx = NULL){
      return $this->_get(1, $idx);
    }
    
    /**
     * Set <certificate> value
     *
     * @param string $value
     * @return \payments\X509Certificates
     */
    public function setCertificate( $value, $idx = NULL){
      return $this->_set(1, $value, $idx);
    }
    
    /**
     * Get all elements of <certificate>
     *
     * @return string[]
     */
    public function getCertificateList(){
     return $this->_get(1);
    }
    
    /**
     * Add a new element to <certificate>
     *
     * @param string $value
     * @return \payments\X509Certificates
     */
    public function addCertificate( $value){
     return $this->_add(1, $value);
    }
  }
}

namespace payments {

  class Payment extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $merchant_data = null;
    
    /**  @var string[]  */
    public $transactions = array();
    
    /**  @var \payments\Output[]  */
    public $refund_to = array();
    
    /**  @var string */
    public $memo = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'payments.Payment');

      // OPTIONAL BYTES merchant_data = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "merchant_data";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // REPEATED BYTES transactions = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "transactions";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $descriptor->addField($f);

      // REPEATED MESSAGE refund_to = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "refund_to";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\payments\Output';
      $descriptor->addField($f);

      // OPTIONAL STRING memo = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "memo";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <merchant_data> has a value
     *
     * @return boolean
     */
    public function hasMerchantData(){
      return $this->_has(1);
    }
    
    /**
     * Clear <merchant_data> value
     *
     * @return \payments\Payment
     */
    public function clearMerchantData(){
      return $this->_clear(1);
    }
    
    /**
     * Get <merchant_data> value
     *
     * @return string
     */
    public function getMerchantData(){
      return $this->_get(1);
    }
    
    /**
     * Set <merchant_data> value
     *
     * @param string $value
     * @return \payments\Payment
     */
    public function setMerchantData( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <transactions> has a value
     *
     * @return boolean
     */
    public function hasTransactions(){
      return $this->_has(2);
    }
    
    /**
     * Clear <transactions> value
     *
     * @return \payments\Payment
     */
    public function clearTransactions(){
      return $this->_clear(2);
    }
    
    /**
     * Get <transactions> value
     *
     * @param int $idx
     * @return string
     */
    public function getTransactions($idx = NULL){
      return $this->_get(2, $idx);
    }
    
    /**
     * Set <transactions> value
     *
     * @param string $value
     * @return \payments\Payment
     */
    public function setTransactions( $value, $idx = NULL){
      return $this->_set(2, $value, $idx);
    }
    
    /**
     * Get all elements of <transactions>
     *
     * @return string[]
     */
    public function getTransactionsList(){
     return $this->_get(2);
    }
    
    /**
     * Add a new element to <transactions>
     *
     * @param string $value
     * @return \payments\Payment
     */
    public function addTransactions( $value){
     return $this->_add(2, $value);
    }
    
    /**
     * Check if <refund_to> has a value
     *
     * @return boolean
     */
    public function hasRefundTo(){
      return $this->_has(3);
    }
    
    /**
     * Clear <refund_to> value
     *
     * @return \payments\Payment
     */
    public function clearRefundTo(){
      return $this->_clear(3);
    }
    
    /**
     * Get <refund_to> value
     *
     * @param int $idx
     * @return \payments\Output
     */
    public function getRefundTo($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <refund_to> value
     *
     * @param \payments\Output $value
     * @return \payments\Payment
     */
    public function setRefundTo(\payments\Output $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <refund_to>
     *
     * @return \payments\Output[]
     */
    public function getRefundToList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <refund_to>
     *
     * @param \payments\Output $value
     * @return \payments\Payment
     */
    public function addRefundTo(\payments\Output $value){
     return $this->_add(3, $value);
    }
    
    /**
     * Check if <memo> has a value
     *
     * @return boolean
     */
    public function hasMemo(){
      return $this->_has(4);
    }
    
    /**
     * Clear <memo> value
     *
     * @return \payments\Payment
     */
    public function clearMemo(){
      return $this->_clear(4);
    }
    
    /**
     * Get <memo> value
     *
     * @return string
     */
    public function getMemo(){
      return $this->_get(4);
    }
    
    /**
     * Set <memo> value
     *
     * @param string $value
     * @return \payments\Payment
     */
    public function setMemo( $value){
      return $this->_set(4, $value);
    }
  }
}

namespace payments {

  class PaymentACK extends \DrSlump\Protobuf\Message {

    /**  @var \payments\Payment */
    public $payment = null;
    
    /**  @var string */
    public $memo = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'payments.PaymentACK');

      // REQUIRED MESSAGE payment = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "payment";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $f->reference = '\payments\Payment';
      $descriptor->addField($f);

      // OPTIONAL STRING memo = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "memo";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <payment> has a value
     *
     * @return boolean
     */
    public function hasPayment(){
      return $this->_has(1);
    }
    
    /**
     * Clear <payment> value
     *
     * @return \payments\PaymentACK
     */
    public function clearPayment(){
      return $this->_clear(1);
    }
    
    /**
     * Get <payment> value
     *
     * @return \payments\Payment
     */
    public function getPayment(){
      return $this->_get(1);
    }
    
    /**
     * Set <payment> value
     *
     * @param \payments\Payment $value
     * @return \payments\PaymentACK
     */
    public function setPayment(\payments\Payment $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <memo> has a value
     *
     * @return boolean
     */
    public function hasMemo(){
      return $this->_has(2);
    }
    
    /**
     * Clear <memo> value
     *
     * @return \payments\PaymentACK
     */
    public function clearMemo(){
      return $this->_clear(2);
    }
    
    /**
     * Get <memo> value
     *
     * @return string
     */
    public function getMemo(){
      return $this->_get(2);
    }
    
    /**
     * Set <memo> value
     *
     * @param string $value
     * @return \payments\PaymentACK
     */
    public function setMemo( $value){
      return $this->_set(2, $value);
    }
  }
}

namespace payments {

  class RecurringPaymentDetails extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $merchant_id = null;
    
    /**  @var string */
    public $subscription_id = null;
    
    /**  @var \payments\RecurringPaymentContract[]  */
    public $contracts = array();
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'payments.RecurringPaymentDetails');

      // REQUIRED STRING merchant_id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "merchant_id";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED BYTES subscription_id = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "subscription_id";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REPEATED MESSAGE contracts = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "contracts";
      $f->type      = \DrSlump\Protobuf::TYPE_MESSAGE;
      $f->rule      = \DrSlump\Protobuf::RULE_REPEATED;
      $f->reference = '\payments\RecurringPaymentContract';
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <merchant_id> has a value
     *
     * @return boolean
     */
    public function hasMerchantId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <merchant_id> value
     *
     * @return \payments\RecurringPaymentDetails
     */
    public function clearMerchantId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <merchant_id> value
     *
     * @return string
     */
    public function getMerchantId(){
      return $this->_get(1);
    }
    
    /**
     * Set <merchant_id> value
     *
     * @param string $value
     * @return \payments\RecurringPaymentDetails
     */
    public function setMerchantId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <subscription_id> has a value
     *
     * @return boolean
     */
    public function hasSubscriptionId(){
      return $this->_has(2);
    }
    
    /**
     * Clear <subscription_id> value
     *
     * @return \payments\RecurringPaymentDetails
     */
    public function clearSubscriptionId(){
      return $this->_clear(2);
    }
    
    /**
     * Get <subscription_id> value
     *
     * @return string
     */
    public function getSubscriptionId(){
      return $this->_get(2);
    }
    
    /**
     * Set <subscription_id> value
     *
     * @param string $value
     * @return \payments\RecurringPaymentDetails
     */
    public function setSubscriptionId( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <contracts> has a value
     *
     * @return boolean
     */
    public function hasContracts(){
      return $this->_has(3);
    }
    
    /**
     * Clear <contracts> value
     *
     * @return \payments\RecurringPaymentDetails
     */
    public function clearContracts(){
      return $this->_clear(3);
    }
    
    /**
     * Get <contracts> value
     *
     * @param int $idx
     * @return \payments\RecurringPaymentContract
     */
    public function getContracts($idx = NULL){
      return $this->_get(3, $idx);
    }
    
    /**
     * Set <contracts> value
     *
     * @param \payments\RecurringPaymentContract $value
     * @return \payments\RecurringPaymentDetails
     */
    public function setContracts(\payments\RecurringPaymentContract $value, $idx = NULL){
      return $this->_set(3, $value, $idx);
    }
    
    /**
     * Get all elements of <contracts>
     *
     * @return \payments\RecurringPaymentContract[]
     */
    public function getContractsList(){
     return $this->_get(3);
    }
    
    /**
     * Add a new element to <contracts>
     *
     * @param \payments\RecurringPaymentContract $value
     * @return \payments\RecurringPaymentDetails
     */
    public function addContracts(\payments\RecurringPaymentContract $value){
     return $this->_add(3, $value);
    }
  }
}

namespace payments {

  class RecurringPaymentContract extends \DrSlump\Protobuf\Message {

    /**  @var string */
    public $contract_id = null;
    
    /**  @var string */
    public $polling_url = null;
    
    /**  @var int */
    public $starts = null;
    
    /**  @var int */
    public $ends = null;
    
    /**  @var int - \payments\PaymentFrequencyType */
    public $payment_frequency_type = null;
    
    /**  @var int */
    public $max_payment_per_period = null;
    
    /**  @var int */
    public $max_payment_amount = null;
    

    /** @var \Closure[] */
    protected static $__extensions = array();

    public static function descriptor()
    {
      $descriptor = new \DrSlump\Protobuf\Descriptor(__CLASS__, 'payments.RecurringPaymentContract');

      // REQUIRED BYTES contract_id = 1
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 1;
      $f->name      = "contract_id";
      $f->type      = \DrSlump\Protobuf::TYPE_BYTES;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED STRING polling_url = 2
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 2;
      $f->name      = "polling_url";
      $f->type      = \DrSlump\Protobuf::TYPE_STRING;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // REQUIRED UINT64 starts = 3
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 3;
      $f->name      = "starts";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_REQUIRED;
      $descriptor->addField($f);

      // OPTIONAL UINT64 ends = 4
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 4;
      $f->name      = "ends";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL ENUM payment_frequency_type = 5
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 5;
      $f->name      = "payment_frequency_type";
      $f->type      = \DrSlump\Protobuf::TYPE_ENUM;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $f->reference = '\payments\PaymentFrequencyType';
      $descriptor->addField($f);

      // OPTIONAL UINT64 max_payment_per_period = 6
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 6;
      $f->name      = "max_payment_per_period";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      // OPTIONAL UINT64 max_payment_amount = 7
      $f = new \DrSlump\Protobuf\Field();
      $f->number    = 7;
      $f->name      = "max_payment_amount";
      $f->type      = \DrSlump\Protobuf::TYPE_UINT64;
      $f->rule      = \DrSlump\Protobuf::RULE_OPTIONAL;
      $descriptor->addField($f);

      foreach (self::$__extensions as $cb) {
        $descriptor->addField($cb(), true);
      }

      return $descriptor;
    }

    /**
     * Check if <contract_id> has a value
     *
     * @return boolean
     */
    public function hasContractId(){
      return $this->_has(1);
    }
    
    /**
     * Clear <contract_id> value
     *
     * @return \payments\RecurringPaymentContract
     */
    public function clearContractId(){
      return $this->_clear(1);
    }
    
    /**
     * Get <contract_id> value
     *
     * @return string
     */
    public function getContractId(){
      return $this->_get(1);
    }
    
    /**
     * Set <contract_id> value
     *
     * @param string $value
     * @return \payments\RecurringPaymentContract
     */
    public function setContractId( $value){
      return $this->_set(1, $value);
    }
    
    /**
     * Check if <polling_url> has a value
     *
     * @return boolean
     */
    public function hasPollingUrl(){
      return $this->_has(2);
    }
    
    /**
     * Clear <polling_url> value
     *
     * @return \payments\RecurringPaymentContract
     */
    public function clearPollingUrl(){
      return $this->_clear(2);
    }
    
    /**
     * Get <polling_url> value
     *
     * @return string
     */
    public function getPollingUrl(){
      return $this->_get(2);
    }
    
    /**
     * Set <polling_url> value
     *
     * @param string $value
     * @return \payments\RecurringPaymentContract
     */
    public function setPollingUrl( $value){
      return $this->_set(2, $value);
    }
    
    /**
     * Check if <starts> has a value
     *
     * @return boolean
     */
    public function hasStarts(){
      return $this->_has(3);
    }
    
    /**
     * Clear <starts> value
     *
     * @return \payments\RecurringPaymentContract
     */
    public function clearStarts(){
      return $this->_clear(3);
    }
    
    /**
     * Get <starts> value
     *
     * @return int
     */
    public function getStarts(){
      return $this->_get(3);
    }
    
    /**
     * Set <starts> value
     *
     * @param int $value
     * @return \payments\RecurringPaymentContract
     */
    public function setStarts( $value){
      return $this->_set(3, $value);
    }
    
    /**
     * Check if <ends> has a value
     *
     * @return boolean
     */
    public function hasEnds(){
      return $this->_has(4);
    }
    
    /**
     * Clear <ends> value
     *
     * @return \payments\RecurringPaymentContract
     */
    public function clearEnds(){
      return $this->_clear(4);
    }
    
    /**
     * Get <ends> value
     *
     * @return int
     */
    public function getEnds(){
      return $this->_get(4);
    }
    
    /**
     * Set <ends> value
     *
     * @param int $value
     * @return \payments\RecurringPaymentContract
     */
    public function setEnds( $value){
      return $this->_set(4, $value);
    }
    
    /**
     * Check if <payment_frequency_type> has a value
     *
     * @return boolean
     */
    public function hasPaymentFrequencyType(){
      return $this->_has(5);
    }
    
    /**
     * Clear <payment_frequency_type> value
     *
     * @return \payments\RecurringPaymentContract
     */
    public function clearPaymentFrequencyType(){
      return $this->_clear(5);
    }
    
    /**
     * Get <payment_frequency_type> value
     *
     * @return int - \payments\PaymentFrequencyType
     */
    public function getPaymentFrequencyType(){
      return $this->_get(5);
    }
    
    /**
     * Set <payment_frequency_type> value
     *
     * @param int - \payments\PaymentFrequencyType $value
     * @return \payments\RecurringPaymentContract
     */
    public function setPaymentFrequencyType( $value){
      return $this->_set(5, $value);
    }
    
    /**
     * Check if <max_payment_per_period> has a value
     *
     * @return boolean
     */
    public function hasMaxPaymentPerPeriod(){
      return $this->_has(6);
    }
    
    /**
     * Clear <max_payment_per_period> value
     *
     * @return \payments\RecurringPaymentContract
     */
    public function clearMaxPaymentPerPeriod(){
      return $this->_clear(6);
    }
    
    /**
     * Get <max_payment_per_period> value
     *
     * @return int
     */
    public function getMaxPaymentPerPeriod(){
      return $this->_get(6);
    }
    
    /**
     * Set <max_payment_per_period> value
     *
     * @param int $value
     * @return \payments\RecurringPaymentContract
     */
    public function setMaxPaymentPerPeriod( $value){
      return $this->_set(6, $value);
    }
    
    /**
     * Check if <max_payment_amount> has a value
     *
     * @return boolean
     */
    public function hasMaxPaymentAmount(){
      return $this->_has(7);
    }
    
    /**
     * Clear <max_payment_amount> value
     *
     * @return \payments\RecurringPaymentContract
     */
    public function clearMaxPaymentAmount(){
      return $this->_clear(7);
    }
    
    /**
     * Get <max_payment_amount> value
     *
     * @return int
     */
    public function getMaxPaymentAmount(){
      return $this->_get(7);
    }
    
    /**
     * Set <max_payment_amount> value
     *
     * @param int $value
     * @return \payments\RecurringPaymentContract
     */
    public function setMaxPaymentAmount( $value){
      return $this->_set(7, $value);
    }
  }
}

